---
- name: Hello World Playbook
  hosts: localhost
  gather_facts: false

  tasks:
    - name: Print Hello World
      debug:
        msg: "Hello, World!"

    - name: Gather facts
      ansible.builtin.setup:
        gather_subset:
          - "min"
          - "hardware"
          - "network"
          - "virtual"
          - "facter"
    - name: Print OS Information
      debug:
        msg: "Operating System: {{ ansible_distribution }} {{ ansible_distribution_version }}"

      
